# https://docs.travis-ci.com/user/languages/go
language: go
go:
  - "1.17"
env:
  - GO111MODULE=on
script:
  - go test -v -cover ./...
  - go vet ./...
  - go get -v -u -d golang.org/x/lint/golint
  - go run golang.org/x/lint/golint -set_exit_status ./...
  - go install honnef.co/go/tools/cmd/staticcheck@latest
  - staticcheck -go 1.17 ./...
notifications:
  email:
    on_success: change
    on_failure: change
